function auto()
{

$(function(){
  var currencies = [/*{ value: 'fever', data: 'fever' },
{ value: 'headache', data: 'headache' },
{ value: 'loss of appetite', data: 'loss of appetite' },
{ value: 'scabs', data: 'scabs' },
{ value: 'infantile paralysis', data: 'infantile paralysis' },
{ value: 'stiffness of neck', data: 'stiffness of neck' },
{ value: 'loss of head support', data: 'loss of head support' },
{ value: 'Severe headache', data: 'Severe headache' },
{ value: 'high fever', data: 'high fever' },
{ value: 'Choking', data: 'Choking' },
{ value: 'fear of water', data: 'fear of water' },
{ value: 'Persistent fever', data: 'Persistent fever' },
{ value: 'coughing', data: 'coughing' },
{ value: 'chest pain', data: 'chest pain' },
{ value: 'general weakness', data: 'general weakness' },
{ value: 'continuous fever', data: 'continuous fever' },
{ value: 'slow pulse rate', data: 'slow pulse rate' },
{ value: 'reddish rashes', data: 'reddish rashes' },
{ value: 'acute diarrohoea', data: 'acute diarrohoea' },
{ value: 'rice watery stool', data: 'rice watery stool' },
{ value: 'muscular cramps', data: 'muscular cramps' },
{ value: 'dehydration', data: 'dehydration' },
{ value: 'nausea', data: 'nausea' },
{ value: 'muscular pain', data: 'muscular pain' },
{ value: 'chilliness', data: 'chilliness' },
{ value: 'shivering', data: 'shivering' },
{ value: 'sweating', data: 'sweating' },
{ value: 'anaemic', data: 'anaemic' },
{ value: 'weakness', data: 'weakness' },
{ value: 'Nausea', data: 'Nausea' },
{ value: 'vomiting', data: 'vomiting' },
{ value: 'body aches', data: 'body aches' },
{ value: 'abdomen pain', data: 'abdomen pain' },
{ value: 'rashes ', data: 'rashes ' },
{ value: 'bleeding from the nose mouth', data: 'bleeding from the nose mouth' },
{ value: 'Black stools', data: 'Black stools' },
{ value: 'excessive thirst', data: 'excessive thirst' },
{ value: 'cold', data: 'cold' },
{ value: 'small white patches', data: 'small white patches' },
{ value: 'rashes', data: 'rashes' },
{ value: 'sore throat', data: 'sore throat' },
{ value: 'muscleaches', data: 'muscleaches' },
{ value: 'chills', data: 'chills' },
{ value: 'fatigue', data: 'fatigue' },
{ value: 'diarrhea', data: 'diarrhea' },
{ value: 'runny nose', data: 'runny nose' },
{ value: 'malaise', data: 'malaise' },
{ value: 'breathing problems', data: 'breathing problems' },
{ value: 'swallowing problems', data: 'swallowing problems' },
{ value: 'extreme headache', data: 'extreme headache' },
{ value: 'neck stiffness', data: 'neck stiffness' },
{ value: 'back stiffness', data: 'back stiffness' },
{ value: 'eye pain', data: 'eye pain' },
{ value: 'sleepy', data: 'sleepy' },
{ value: 'low grade fever', data: 'low grade fever' },
{ value: 'Intense itching', data: 'Intense itching' },
{ value: 'skin rash', data: 'skin rash' },
{ value: 'loss of sleep', data: 'loss of sleep' },
{ value: 'pain in swaolling', data: 'pain in swaolling' },
{ value: 'stomachaches', data: 'stomachaches' },
{ value: 'headaches', data: 'headaches' },
{ value: 'stiff neck', data: 'stiff neck' },
{ value: 'scratchy voice', data: 'scratchy voice' },
{ value: 'swollen tonsils', data: 'swollen tonsils' },
{ value: 'white patches on throat', data: 'white patches on throat' },
{ value: 'red dots on mouth', data: 'red dots on mouth' },
{ value: 'appetite loss', data: 'appetite loss' },
{ value: 'stomachache', data: 'stomachache' },
{ value: 'vomitting', data: 'vomitting' },
{ value: 'rash', data: 'rash' },
{ value: 'agitation', data: 'agitation' },
{ value: 'swelling of lumph nodes', data: 'swelling of lumph nodes' },
{ value: 'blood in stools', data: 'blood in stools' },
{ value: 'muscle aches', data: 'muscle aches' },
{ value: 'joint pain', data: 'joint pain' },
{ value: 'Swollen lymph nodes', data: 'Swollen lymph nodes' },
{ value: 'Night sweats', data: 'Night sweats' },
{ value: 'dirrehrea', data: 'dirrehrea' },
{ value: 'extreme fever', data: 'extreme fever' },
{ value: 'red rash', data: 'red rash' },
{ value: 'breathing difficulty', data: 'breathing difficulty' },
{ value: 'muscle pain', data: 'muscle pain' },
{ value: 'diarrhoea', data: 'diarrhoea' },
{ value: 'dark urine', data: 'dark urine' },
{ value: 'weight loss', data: 'weight loss' },
{ value: 'itching', data: 'itching' },
{ value: 'yellow skin', data: 'yellow skin' },
{ value: 'yellow eyes', data: 'yellow eyes' },
{ value: 'tiredness', data: 'tiredness' },
{ value: 'general aches', data: 'general aches' },
{ value: 'feeling unwell', data: 'feeling unwell' },
{ value: 'jaundice', data: 'jaundice' },
{ value: 'pale grey coloured poo', data: 'pale grey coloured poo' },
{ value: 'feeling tired', data: 'feeling tired' },
{ value: 'feeling sick', data: 'feeling sick' },
{ value: 'brain fog', data: 'brain fog' },
{ value: 'mood swings', data: 'mood swings' },
{ value: 'anxiety', data: 'anxiety' },
{ value: 'bloating', data: 'bloating' },
{ value: 'itchy skin', data: 'itchy skin' },
{ value: 'cough', data: 'cough' },
{ value: 'sneezing', data: 'sneezing' },
{ value: 'restlessness', data: 'restlessness' },
{ value: 'a sense of dread', data: 'a sense of dread' },
{ value: 'difficulty concentrating', data: 'difficulty concentrating' },
{ value: 'irritability', data: 'irritability' },
{ value: 'stomach cramps', data: 'stomach cramps' },
{ value: 'sudden fever', data: 'sudden fever' },
{ value: 'chesty cough', data: 'chesty cough' },
{ value: 'aching muscles', data: 'aching muscles' },
{ value: 'runny or blocked nose', data: 'runny or blocked nose' },
{ value: 'difficulty sleeping', data: 'difficulty sleeping' },
{ value: 'red and swollen gums', data: 'red and swollen gums' },
{ value: 'bleeding gums', data: 'bleeding gums' },
{ value: 'bad breath', data: 'bad breath' },
{ value: 'unpleasant taste in mouth', data: 'unpleasant taste in mouth' },
{ value: 'loose teeth', data: 'loose teeth' },
{ value: 'gum abscesses', data: 'gum abscesses' },*/
{ value: 'fever', data: 'fever' },
{ value: 'headache', data: 'headache' },
{ value: 'loss of appetite', data: 'loss of appetite' },
{ value: 'scabs', data: 'scabs' },
{ value: 'infantile paralysis', data: 'infantile paralysis' },
{ value: 'stiffness of neck', data: 'stiffness of neck' },
{ value: 'loss of head support', data: 'loss of head support' },
{ value: 'severe headache', data: 'severe headache' },
{ value: 'high fever', data: 'high fever' },
{ value: 'choking', data: 'choking' },
{ value: 'fear of water', data: 'fear of water' },
{ value: 'persistent fever', data: 'persistent fever' },
{ value: 'cough', data: 'cough' },
{ value: 'chest pain', data: 'chest pain' },
{ value: 'general weakness', data: 'general weakness' },
{ value: 'slow pulse rate', data: 'slow pulse rate' },
{ value: 'reddish rashes', data: 'reddish rashes' },
{ value: 'acute diarrhea', data: 'acute diarrhea' },
{ value: 'rice watery stool', data: 'rice watery stool' },
{ value: 'muscular cramps', data: 'muscular cramps' },
{ value: 'dehydration', data: 'dehydration' },
{ value: 'rapid pulse', data: 'rapid pulse' },
{ value: 'abdominal cramps', data: 'abdominal cramps' },
{ value: 'nausea', data: 'nausea' },
{ value: 'muscle aches', data: 'muscle aches' },
{ value: 'chilliness', data: 'chilliness' },
{ value: 'shivering', data: 'shivering' },
{ value: 'sweating', data: 'sweating' },
{ value: 'anaemic', data: 'anaemic' },
{ value: 'weakness', data: 'weakness' },
{ value: 'vomiting', data: 'vomiting' },
{ value: 'body aches', data: 'body aches' },
{ value: 'abdomen pain', data: 'abdomen pain' },
{ value: 'rashes', data: 'rashes' },
{ value: 'bleeding from the nose mouth', data: 'bleeding from the nose mouth' },
{ value: 'black stools', data: 'black stools' },
{ value: 'excessive thirst', data: 'excessive thirst' },
{ value: 'cold', data: 'cold' },
{ value: 'small white patches', data: 'small white patches' },
{ value: 'sneezing', data: 'sneezing' },
{ value: 'watery eyes', data: 'watery eyes' },
{ value: 'tiednessness', data: 'tiednessness' },
{ value: 'aches', data: 'aches' },
{ value: 'sore throat', data: 'sore throat' },
{ value: 'chills', data: 'chills' },
{ value: 'fatigue', data: 'fatigue' },
{ value: 'diarrhea', data: 'diarrhea' },
{ value: 'runny nose', data: 'runny nose' },
{ value: 'malaise', data: 'malaise' },
{ value: 'breathing problems', data: 'breathing problems' },
{ value: 'swallowing problems', data: 'swallowing problems' },
{ value: 'extreme headache', data: 'extreme headache' },
{ value: 'neck stiffness', data: 'neck stiffness' },
{ value: 'back stiffness', data: 'back stiffness' },
{ value: 'eye pain', data: 'eye pain' },
{ value: 'feeling sleepy', data: 'feeling sleepy' },
{ value: 'low grade fever', data: 'low grade fever' },
{ value: 'intense itching', data: 'intense itching' },
{ value: 'skin rashes', data: 'skin rashes' },
{ value: 'red blotches', data: 'red blotches' },
{ value: 'loss of sleep', data: 'loss of sleep' },
{ value: 'sores', data: 'sores' },
{ value: 'pain in swaolling', data: 'pain in swaolling' },
{ value: 'stomachache', data: 'stomachache' },
{ value: 'stiff neck', data: 'stiff neck' },
{ value: 'scratchy voice', data: 'scratchy voice' },
{ value: 'swollen tonsils', data: 'swollen tonsils' },
{ value: 'white patches on throat', data: 'white patches on throat' },
{ value: 'red dots on mouth', data: 'red dots on mouth' },
{ value: 'appetite loss', data: 'appetite loss' },
{ value: 'agitation', data: 'agitation' },
{ value: 'swelling of lumph nodes', data: 'swelling of lumph nodes' },
{ value: 'blood in stools', data: 'blood in stools' },
{ value: 'joint pain', data: 'joint pain' },
{ value: 'swollen lymph nodes', data: 'swollen lymph nodes' },
{ value: 'night sweats', data: 'night sweats' },
{ value: 'extreme fever', data: 'extreme fever' },
{ value: 'red rashes', data: 'red rashes' },
{ value: 'breathing difficulty', data: 'breathing difficulty' },
{ value: 'dark urine', data: 'dark urine' },
{ value: 'weight loss', data: 'weight loss' },
{ value: 'itching', data: 'itching' },
{ value: 'yellow skin', data: 'yellow skin' },
{ value: 'yellow eyes', data: 'yellow eyes' },
{ value: 'tiredness', data: 'tiredness' },
{ value: 'general aches', data: 'general aches' },
{ value: 'feeling unwell', data: 'feeling unwell' },
{ value: 'jaundice', data: 'jaundice' },
{ value: 'pale grey coloured poo', data: 'pale grey coloured poo' },
{ value: 'tiedness', data: 'tiedness' },
{ value: 'feeling sick', data: 'feeling sick' },
{ value: 'brain fog', data: 'brain fog' },
{ value: 'mood swings', data: 'mood swings' },
{ value: 'anxiety', data: 'anxiety' },
{ value: 'bloating', data: 'bloating' },
{ value: 'itchy skin', data: 'itchy skin' },
{ value: 'abdominal pain', data: 'abdominal pain' },
{ value: 'acute liver failure', data: 'acute liver failure' },
{ value: 'restlessness', data: 'restlessness' },
{ value: 'a sense of dread', data: 'a sense of dread' },
{ value: 'difficulty concentrating', data: 'difficulty concentrating' },
{ value: 'irritability', data: 'irritability' },
{ value: 'stomach cramps', data: 'stomach cramps' },
{ value: 'sudden fever', data: 'sudden fever' },
{ value: 'chesty cough', data: 'chesty cough' },
{ value: 'runny or blocked nose', data: 'runny or blocked nose' },
{ value: 'difficulty sleeping', data: 'difficulty sleeping' },
{ value: 'red and swollen gums', data: 'red and swollen gums' },
{ value: 'bleeding gums', data: 'bleeding gums' },
{ value: 'bad breath', data: 'bad breath' },
{ value: 'unpleasant taste in mouth', data: 'unpleasant taste in mouth' },
{ value: 'loose teeth', data: 'loose teeth' },
{ value: 'gum abscesses', data: 'gum abscesses' },
{ value: 'excessive gas', data: 'excessive gas' },
{ value: 'greasy stools', data: 'greasy stools' },
{ value: 'hemorrhage', data: 'hemorrhage' },
{ value: 'dizziness', data: 'dizziness' },
{ value: 'bleeding under the skin', data: 'bleeding under the skin' },
{ value: 'bleeding from internal organs', data: 'bleeding from internal organs' },
{ value: 'extreme fatigue', data: 'extreme fatigue' },
{ value: 'watery diarrhea', data: 'watery diarrhea' },
{ value: 'watery or bloody diarrhea', data: 'watery or bloody diarrhea' },
{ value: 'breathing problem', data: 'breathing problem' },
{ value: 'shaking', data: 'shaking' },
{ value: 'sensitivity to light', data: 'sensitivity to light' },
{ value: 'decreased urination', data: 'decreased urination' },
{ value: 'bleeding from nose', data: 'bleeding from nose' },
{ value: 'stomach pain', data: 'stomach pain' },
{ value: 'red eyes', data: 'red eyes' },
{ value: 'raised rashes', data: 'raised rashes' },
{ value: 'skin infection', data: 'skin infection' },
{ value: 'urinary tract infection', data: 'urinary tract infection' },
{ value: 'blood poisoning', data: 'blood poisoning' },
{ value: 'lung infection', data: 'lung infection' },
{ value: 'painful and pus-filled pimples', data: 'painful and pus-filled pimples' },
{ value: 'feeling uncomfortably full', data: 'feeling uncomfortably full' },
{ value: 'belching', data: 'belching' },
{ value: 'reflux', data: 'reflux' },
{ value: 'trembling', data: 'trembling' },
{ value: 'churning stomach', data: 'churning stomach' },
{ value: 'red and watery eyes', data: 'red and watery eyes' },
{ value: 'slightly raised temperature', data: 'slightly raised temperature' },
{ value: 'severe pain in joints', data: 'severe pain in joints' },
{ value: 'joint feeling hot', data: 'joint feeling hot' },
{ value: 'swelling in joint', data: 'swelling in joint' },
{ value: 'shiny skin over joint', data: 'shiny skin over joint' },
{ value: 'migraine', data: 'migraine' },
{ value: 'labyrinthitis', data: 'labyrinthitis' },
{ value: 'stress', data: 'stress' },
{ value: 'postural hypotension', data: 'postural hypotension' },
{ value: 'vertebrobasilar insufficiency', data: 'vertebrobasilar insufficiency' },
{ value: 'tearful', data: 'tearful' },
{ value: 'guilty', data: 'guilty' },
{ value: 'low self-esteem', data: 'low self-esteem' },
{ value: 'hopeless & helpless', data: 'hopeless & helpless' },
{ value: 'loss of energy', data: 'loss of energy' },
{ value: 'eye redness', data: 'eye redness' },
{ value: 'discharge', data: 'discharge' },
{ value: 'burning sensation in eyes', data: 'burning sensation in eyes' },
{ value: 'sticky coating on the eyelashes', data: 'sticky coating on the eyelashes' },
{ value: 'muscle spasms', data: 'muscle spasms' },
{ value: 'having an abnormal', data: 'having an abnormal' },
{ value: 'twisted posture a foot', data: 'twisted posture a foot' },
{ value: 'leg or arm turning inwards', data: 'leg or arm turning inwards' },
{ value: 'body parts jerking rapidly', data: 'body parts jerking rapidly' },
{ value: 'hair loss', data: 'hair loss' },
{ value: 'delayed wound healing', data: 'delayed wound healing' },
{ value: 'poor concentration', data: 'poor concentration' },
{ value: 'frequently getting infections', data: 'frequently getting infections' },
{ value: 'depression', data: 'depression' },
{ value: 'difficulty keeping warm', data: 'difficulty keeping warm' },
{ value: 'bleeding from the nose and gums', data: 'bleeding from the nose and gums' },
{ value: 'rapid breathing', data: 'rapid breathing' },
{ value: 'shortness of breath', data: 'shortness of breath' },
{ value: 'exhaustion', data: 'exhaustion' },
{ value: 'severe weight loss', data: 'severe weight loss' },
{ value: 'bleeding from eyes', data: 'bleeding from eyes' },
{ value: 'bruising', data: 'bruising' },
{ value: 'increased thirst', data: 'increased thirst' },
{ value: 'urinate frequently', data: 'urinate frequently' },
{ value: 'low mood', data: 'low mood' },
{ value: 'lethargy', data: 'lethargy' },
{ value: 'craving for salty foods', data: 'craving for salty foods' },
{ value: 'mental confusion', data: 'mental confusion' },
{ value: 'slurred speech', data: 'slurred speech' },
{ value: 'loss of co-ordination', data: 'loss of co-ordination' },
{ value: 'slow breathing', data: 'slow breathing' },
{ value: 'hypothermia', data: 'hypothermia' },
{ value: 'stupor', data: 'stupor' },
{ value: 'being unconscious', data: 'being unconscious' },
{ value: 'constipation', data: 'constipation' },
{ value: 'cramping', data: 'cramping' },
{ value: 'anaemia', data: 'anaemia' },
{ value: 'dermatitis herpetiformis', data: 'dermatitis herpetiformis' },
{ value: 'tooth enamel problems', data: 'tooth enamel problems' },
{ value: 'bark-like cough', data: 'bark-like cough' },
{ value: 'croaky voice', data: 'croaky voice' },
{ value: 'difficulty breathing', data: 'difficulty breathing' },
{ value: 'stridor', data: 'stridor' },
{ value: 'swollen glands', data: 'swollen glands' },
{ value: 'producing more saliva than normal', data: 'producing more saliva than normal' },
{ value: 'pain', data: 'pain' },
{ value: 'itchy blisters', data: 'itchy blisters' },
{ value: 'burning', data: 'burning' },
{ value: 'tingling', data: 'tingling' },
{ value: 'numbness', data: 'numbness' },
{ value: 'paralysis of one side of the body', data: 'paralysis of one side of the body' },
{ value: 'sudden loss', data: 'sudden loss' },
{ value: 'loss of consciousness', data: 'loss of consciousness' },
{ value: 'difficulty swallowing', data: 'difficulty swallowing' },
{ value: 'problems with balance', data: 'problems with balance' },
{ value: 'toothache', data: 'toothache' },
{ value: 'tooth sensitivity', data: 'tooth sensitivity' },
{ value: 'brown or black spots appearing on your teeth', data: 'brown or black spots appearing on your teeth' },
{ value: 'unpleasant taste in your mouth', data: 'unpleasant taste in your mouth' },
{ value: 'suddenly feeling sick', data: 'suddenly feeling sick' },
{ value: 'projectile vomiting', data: 'projectile vomiting' },
{ value: 'slight fever', data: 'slight fever' },
{ value: 'painful stomach cramps', data: 'painful stomach cramps' },
{ value: 'aching limbs', data: 'aching limbs' },
{ value: 'bloody diarrhea', data: 'bloody diarrhea' },
{ value: 'sudden onset of fever', data: 'sudden onset of fever' },
{ value: 'muscular aches', data: 'muscular aches' },
{ value: 'rheumatic fever', data: 'rheumatic fever' },
{ value: 'backache', data: 'backache' },
{ value: 'tired', data: 'tired' },
{ value: 'problems breathing', data: 'problems breathing' },
{ value: 'loss of alertness', data: 'loss of alertness' },
{ value: 'sudden onset', data: 'sudden onset' },
{ value: 'behavioral changes', data: 'behavioral changes' },
{ value: 'scratching of scalp', data: 'scratching of scalp' },
{ value: 'presence of live lice', data: 'presence of live lice' },
{ value: 'pinpoint sized white eggs', data: 'pinpoint sized white eggs' },
{ value: 'pinkish bumps with flate top on skin', data: 'pinkish bumps with flate top on skin' },
{ value: 'itching at the site of rashes', data: 'itching at the site of rashes' },
{ value: 'lacy-white lesions in mouth', data: 'lacy-white lesions in mouth' },
{ value: 'blisters', data: 'blisters' },
{ value: 'white patches', data: 'white patches' },
{ value: 'reddened area of skin ring shape', data: 'reddened area of skin ring shape' },
{ value: 'raised blisters on border of rashes', data: 'raised blisters on border of rashes' },
{ value: 'itching rashes', data: 'itching rashes' },
{ value: 'burning rashes', data: 'burning rashes' },
{ value: 'peeling of skin', data: 'peeling of skin' },
{ value: 'stinging sensation', data: 'stinging sensation' },
{ value: 'swelling', data: 'swelling' },
{ value: 'darkening of the skin', data: 'darkening of the skin' },
{ value: 'ring shapped red rashes', data: 'ring shapped red rashes' },
{ value: 'itchy scalp', data: 'itchy scalp' },
  ];
  $(document).ready(function () {
  	$('.autocomplete').autocomplete({
    lookup: currencies,
    onSelect: function (suggestion) {
      var thehtml = '<strong>Currency Name:</strong> ' + suggestion.value + ' <br> <strong>Symbol:</strong> ' + suggestion.data;
      $('#outputcontent').html(thehtml);
    }
  });
  
  });
  

});
}
