function auto()
{

$(function(){
  var currencies = [{ value: 'fever', data: 'fever' },
{ value: 'headache', data: 'headache' },
{ value: 'loss of appetite', data: 'loss of appetite' },
{ value: 'scabs', data: 'scabs' },
{ value: 'infantile paralysis', data: 'infantile paralysis' },
{ value: 'stiffness of neck', data: 'stiffness of neck' },
{ value: 'loss of head support', data: 'loss of head support' },
{ value: 'Severe headache', data: 'Severe headache' },
{ value: 'high fever', data: 'high fever' },
{ value: 'Choking', data: 'Choking' },
{ value: 'fear of water', data: 'fear of water' },
{ value: 'Persistent fever', data: 'Persistent fever' },
{ value: 'coughing', data: 'coughing' },
{ value: 'chest pain', data: 'chest pain' },
{ value: 'general weakness', data: 'general weakness' },
{ value: 'continuous fever', data: 'continuous fever' },
{ value: 'slow pulse rate', data: 'slow pulse rate' },
{ value: 'reddish rashes', data: 'reddish rashes' },
{ value: 'acute diarrohoea', data: 'acute diarrohoea' },
{ value: 'rice watery stool', data: 'rice watery stool' },
{ value: 'muscular cramps', data: 'muscular cramps' },
{ value: 'dehydration', data: 'dehydration' },
{ value: 'nausea', data: 'nausea' },
{ value: 'muscular pain', data: 'muscular pain' },
{ value: 'chilliness', data: 'chilliness' },
{ value: 'shivering', data: 'shivering' },
{ value: 'sweating', data: 'sweating' },
{ value: 'anaemic', data: 'anaemic' },
{ value: 'weakness', data: 'weakness' },
{ value: 'Nausea', data: 'Nausea' },
{ value: 'vomiting', data: 'vomiting' },
{ value: 'body aches', data: 'body aches' },
{ value: 'abdomen pain', data: 'abdomen pain' },
{ value: 'rashes ', data: 'rashes ' },
{ value: 'bleeding from the nose mouth', data: 'bleeding from the nose mouth' },
{ value: 'Black stools', data: 'Black stools' },
{ value: 'excessive thirst', data: 'excessive thirst' },
{ value: 'cold', data: 'cold' },
{ value: 'small white patches', data: 'small white patches' },
{ value: 'rashes', data: 'rashes' },
{ value: 'sore throat', data: 'sore throat' },
{ value: 'muscleaches', data: 'muscleaches' },
{ value: 'chills', data: 'chills' },
{ value: 'fatigue', data: 'fatigue' },
{ value: 'diarrhea', data: 'diarrhea' },
{ value: 'runny nose', data: 'runny nose' },
{ value: 'malaise', data: 'malaise' },
{ value: 'breathing problems', data: 'breathing problems' },
{ value: 'swallowing problems', data: 'swallowing problems' },
{ value: 'extreme headache', data: 'extreme headache' },
{ value: 'neck stiffness', data: 'neck stiffness' },
{ value: 'back stiffness', data: 'back stiffness' },
{ value: 'eye pain', data: 'eye pain' },
{ value: 'sleepy', data: 'sleepy' },
{ value: 'low grade fever', data: 'low grade fever' },
{ value: 'Intense itching', data: 'Intense itching' },
{ value: 'skin rash', data: 'skin rash' },
{ value: 'loss of sleep', data: 'loss of sleep' },
{ value: 'pain in swaolling', data: 'pain in swaolling' },
{ value: 'stomachaches', data: 'stomachaches' },
{ value: 'headaches', data: 'headaches' },
{ value: 'stiff neck', data: 'stiff neck' },
{ value: 'scratchy voice', data: 'scratchy voice' },
{ value: 'swollen tonsils', data: 'swollen tonsils' },
{ value: 'white patches on throat', data: 'white patches on throat' },
{ value: 'red dots on mouth', data: 'red dots on mouth' },
{ value: 'appetite loss', data: 'appetite loss' },
{ value: 'stomachache', data: 'stomachache' },
{ value: 'vomitting', data: 'vomitting' },
{ value: 'rash', data: 'rash' },
{ value: 'agitation', data: 'agitation' },
{ value: 'swelling of lumph nodes', data: 'swelling of lumph nodes' },
{ value: 'blood in stools', data: 'blood in stools' },
{ value: 'muscle aches', data: 'muscle aches' },
{ value: 'joint pain', data: 'joint pain' },
{ value: 'Swollen lymph nodes', data: 'Swollen lymph nodes' },
{ value: 'Night sweats', data: 'Night sweats' },
{ value: 'dirrehrea', data: 'dirrehrea' },
{ value: 'extreme fever', data: 'extreme fever' },
{ value: 'red rash', data: 'red rash' },
{ value: 'breathing difficulty', data: 'breathing difficulty' },
{ value: 'muscle pain', data: 'muscle pain' },
{ value: 'diarrhoea', data: 'diarrhoea' },
{ value: 'dark urine', data: 'dark urine' },
{ value: 'weight loss', data: 'weight loss' },
{ value: 'itching', data: 'itching' },
{ value: 'yellow skin', data: 'yellow skin' },
{ value: 'yellow eyes', data: 'yellow eyes' },
{ value: 'tiredness', data: 'tiredness' },
{ value: 'general aches', data: 'general aches' },
{ value: 'feeling unwell', data: 'feeling unwell' },
{ value: 'jaundice', data: 'jaundice' },
{ value: 'pale grey coloured poo', data: 'pale grey coloured poo' },
{ value: 'feeling tired', data: 'feeling tired' },
{ value: 'feeling sick', data: 'feeling sick' },
{ value: 'brain fog', data: 'brain fog' },
{ value: 'mood swings', data: 'mood swings' },
{ value: 'anxiety', data: 'anxiety' },
{ value: 'bloating', data: 'bloating' },
{ value: 'itchy skin', data: 'itchy skin' },
{ value: 'cough', data: 'cough' },
{ value: 'sneezing', data: 'sneezing' },
{ value: 'restlessness', data: 'restlessness' },
{ value: 'a sense of dread', data: 'a sense of dread' },
{ value: 'difficulty concentrating', data: 'difficulty concentrating' },
{ value: 'irritability', data: 'irritability' },
{ value: 'stomach cramps', data: 'stomach cramps' },
{ value: 'sudden fever', data: 'sudden fever' },
{ value: 'chesty cough', data: 'chesty cough' },
{ value: 'aching muscles', data: 'aching muscles' },
{ value: 'runny or blocked nose', data: 'runny or blocked nose' },
{ value: 'difficulty sleeping', data: 'difficulty sleeping' },
{ value: 'red and swollen gums', data: 'red and swollen gums' },
{ value: 'bleeding gums', data: 'bleeding gums' },
{ value: 'bad breath', data: 'bad breath' },
{ value: 'unpleasant taste in mouth', data: 'unpleasant taste in mouth' },
{ value: 'loose teeth', data: 'loose teeth' },
{ value: 'gum abscesses', data: 'gum abscesses' },
  ];
  $(document).ready(function () {
  	$('.autocomplete').autocomplete({
    lookup: currencies,
    onSelect: function (suggestion) {
      var thehtml = '<strong>Currency Name:</strong> ' + suggestion.value + ' <br> <strong>Symbol:</strong> ' + suggestion.data;
      $('#outputcontent').html(thehtml);
    }
  });
  
  });
  

});
}
